language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install: composer install --no-interaction --prefer-source --no-scripts
script: php -r "copy('.env.sample', '.env');" && php webroot/index.php configure -vv -k && php webroot/index.php updare -vv && php webroot/index.php seed