language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install: composer install --no-interaction --prefer-source --no-scripts --dev
script: php -r "copy('.env.sample', '.env');" && php webroot/index.php configure -vv -k && php webroot/index.php update -vv && php webroot/index.php seed && phpunit