language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

allow_failures:
  - php: hhvm

install: composer install --no-interaction --prefer-source --no-scripts
script: php webroot/index.php configure -v -k